### ISSUE TITLE
需要将sherpa绑定到button吗，绑定上去以后点一下unity就崩溃了

### ISSUE THREAD

**Issue by JiYueBo666** [ssssssilver/sherpa-ncnn-unity#2]
![32e46e8143d827954b838725d70393dc](https://github.com/ssssssilver/sherpa-ncnn-unity/assets/121330570/6342268c-3b64-47ea-9a5e-a43a8a563023)

**Comment by ssssssilver** [comment]
不需要  检查一下有没有麦克风

**Comment by JiYueBo666** [comment]
> 不需要 检查一下有没有麦克风

后来检查了一下是初始化配置那里没给对。现在把路径哪里都改成了直接给绝对路径。但是创建识别器和在线流这块还是有问题。
‘’‘
 private string tokensPath= "C://Users/admin/draw/Assets/StreamingAssets/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/tokens.txt";
        private string encoderParamPath= "C://Users/admin/draw/Assets/StreamingAssets/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/encoder_jit_trace-pnnx.ncnn.param";
        private string encoderBinPath= "C://Users/admin/draw/Assets/StreamingAssets/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/encoder_jit_trace-pnnx.ncnn.bin";
        private string decoderParamPath= "C://Users/admin/draw/Assets/StreamingAssets/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/decoder_jit_trace-pnnx.ncnn.param";
        private string decoderBinPath= "C://Users/admin/draw/Assets/StreamingAssets/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/decoder_jit_trace-pnnx.ncnn.bin";
        private string joinerParamPath= "C://Users/admin/draw/Assets/StreamingAssets/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/joiner_jit_trace-pnnx.ncnn.param";
        private string joinerBinPath="C://Users/admin/draw/Assets/StreamingAssets/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/joiner_jit_trace-pnnx.ncnn.bin";
        private int numThreads = 1;
        private string decodingMethod = "greedy_search";
        

       
        void Start()
        {

            Debug.Log("begin");



            //Debug.Log(tokensPath);=
            // 初始化配置
            SherpaNcnn.OnlineRecognizerConfig config = new SherpaNcnn.OnlineRecognizerConfig
            {
                FeatConfig = { SampleRate = 16000, FeatureDim = 80 },
                ModelConfig = 
                {
                Tokens=tokensPath,
                EncoderParam=encoderParamPath,
                EncoderBin=encoderBinPath,
                DecoderParam=decoderParamPath,
                DecoderBin=decoderBinPath,
                JoinerParam=joinerParamPath,
                JoinerBin=joinerBinPath,
                UseVulkanCompute = 0,
                NumThreads = numThreads
            },
                DecoderConfig = 
            {
                DecodingMethod = decodingMethod,
                NumActivePaths = 4
            },
                EnableEndpoint = 1,
                Rule1MinTrailingSilence = 2.4F,
                Rule2MinTrailingSilence = 1.2F,
                Rule3MinUtteranceLength = 20.0F
            };

            Debug.Log(tokensPath);

            // 创建识别器和在线流
            recognizer = new SherpaNcnn.OnlineRecognizer(config);’‘’

**Comment by JiYueBo666** [comment]
我的问题描述不明确，重新开一个issue
