### ISSUE TITLE
Demo初始化模型时候闪退

### ISSUE THREAD

**Issue by JiYueBo666** [ssssssilver/sherpa-ncnn-unity#3]
经过测试，发现脚本在执行到第60行，也就是加载config，创建识别器和在线流时候会发生闪退。
``
        private SherpaNcnn.OnlineRecognizer recognizer;
        private SherpaNcnn.OnlineStream onlineStream;
        private int segmentIndex = 0;
        private string lastText = "";
        [SerializeField]
        private Text Text;
        [SerializeField]
        private Text buttonTxt;

        // 可以在Unity编辑器中设置这些参数
        public string tokensPath;
        public string encoderParamPath;
        public string encoderBinPath;
        public string decoderParamPath;
        public string decoderBinPath;
        public string joinerParamPath;
        public string joinerBinPath;
        public int numThreads = 1;
        public string decodingMethod = "greedy_search";

        void Start()
        {
            // 初始化配置
            SherpaNcnn.OnlineRecognizerConfig config = new SherpaNcnn.OnlineRecognizerConfig
            {
                FeatConfig = { SampleRate = 16000, FeatureDim = 80 },
                ModelConfig = {
                Tokens = Path.Combine(Application.streamingAssetsPath,tokensPath),
                EncoderParam =  Path.Combine(Application.streamingAssetsPath,encoderParamPath),
                EncoderBin =Path.Combine(Application.streamingAssetsPath, encoderBinPath),
                DecoderParam =Path.Combine(Application.streamingAssetsPath, decoderParamPath),
                DecoderBin = Path.Combine(Application.streamingAssetsPath, decoderBinPath),
                JoinerParam = Path.Combine(Application.streamingAssetsPath,joinerParamPath),
                JoinerBin =Path.Combine(Application.streamingAssetsPath,joinerBinPath),
                UseVulkanCompute = 0,
                NumThreads = numThreads
            },
                DecoderConfig = {
                DecodingMethod = decodingMethod,
                NumActivePaths = 4
            },
                EnableEndpoint = 1,
                Rule1MinTrailingSilence = 2.4F,
                Rule2MinTrailingSilence = 1.2F,
                Rule3MinUtteranceLength = 20.0F
            };

            // 创建识别器和在线流
            recognizer = new SherpaNcnn.OnlineRecognizer(config);
``

我查看了Unity的Log，向GPT提问以后他解释的原因是：尝试在Unity应用中通过sherpa-ncnn-core加载或初始化某个深度学习模型时，ncnn库在构建卷积层的硬件加速管道时遇到了内存访问违规。这可能是由于模型定义有误、模型文件损坏、硬件兼容性问题、或者是ncnn库与当前运行环境的某些配置不匹配所导致的。

请问我需要做哪些修改？（刚接触Unity，希望大佬回复）

**Comment by ssssssilver** [comment]
你当前使用的是什么平台

**Comment by JiYueBo666** [comment]
> 你当前使用的是什么平台

Windows平台，Unity2020.3.48.f1c1

**Comment by JiYueBo666** [comment]
已经可以正常运行了！我查看了sherpa给出的文档 [https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#id9]。文档中，modelconfig给出的numThread=2。您的示例中给出的numThread=1。我改成2以后可以正常运行了。
感谢您提供的Unity方案！

**Comment by yunjn** [comment]
2022.3.12f1c1同样存在闪退的问题

**Comment by csukuangfj** [comment]
能否获取有用的 log, 以供调试？

**Comment by yunjn** [comment]
同样是创建识别器那闪退，用unity hub转换下编辑器版本就不闪退了，应该是unity项目配置的问题

**Comment by yuyun2000** [comment]
> 同样是创建识别器那闪退，用unity hub转换下编辑器版本就不闪退了，应该是unity项目配置的问题

难道你也姓云

**Comment by JiYueBo666** [comment]
按照sharp-necc的相关文档中配置，thread=2. demo中thread=1,。我修改为2以后，重新走一遍流程，有时候可以成功使用。

**Comment by yuyun2000** [comment]
> 按照sharp-necc的相关文档中配置，thread=2. demo中thread=1,。我修改为2以后，重新走一遍流程，有时候可以成功使用。

纠正一下，是sherpa-ncnn

**Comment by twosapling** [comment]
unity项目里的Licensing签名认证失败导致的闪崩，新建项目拷贝模型和代码就好了。（或更新许可证可能也好了)
