### ISSUE TITLE
大佬，安卓环境怎们集成

### ISSUE THREAD

**Issue by myrider** [ssssssilver/sherpa-ncnn-unity#4]
大佬，安卓环境怎们集成，给说下呗

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/ncnn/android/index.html
可以看这个文档

---

https://github.com/k2-fsa/sherpa-ncnn/releases
 这里有编译好的 android apk 下载.

**Comment by myrider** [comment]
我想在untiy的安卓环境使用这个库，”https://github.com/k2-fsa/sherpa-ncnn/releases“这里边的apk我解压后，把里边的so文件复制到untiy下，但不知道怎们使用啊，能教教吗？或哪有这样的教程。






407133313
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssilver/sherpa-ncnn-unity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月11日(星期天) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssilver/sherpa-ncnn-unity] 大佬，安卓环境怎们集成 (Issue #4)





 
https://k2-fsa.github.io/sherpa/ncnn/android/index.html
 可以看这个文档
 
 
https://github.com/k2-fsa/sherpa-ncnn/releases
 这里有编译好的 android apk 下载.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-ncnn/blob/master/build-android-arm64-v8a.sh#L53
把上面一行的 OFF 改成 ON, 然后你运行它，就能得到你所需要的所有的 .so 文件。

**Comment by ssssssilver** [comment]
已经接入android
