### ISSUE TITLE
编译为window下的dll问题

### ISSUE THREAD

**Issue by twosapling** [ssssssilver/sherpa-ncnn-unity#5]
目录Assets/Sherpa-ncnn/plugins下的dll文件在哪里下载的？还是自己编译出来的？
我看“https://k2-fsa.github.io/sherpa/ncnn/install/windows.html#bit-windows-x64”编译出来的是exe文件，你是怎们编译dll的啊？

**Comment by csukuangfj** [comment]
请参考
https://k2-fsa.github.io/sherpa/ncnn/install/windows.html

你需要把  `-DBUILD_SHARED_LIBS=ON` 传给 cmake
